<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (name?,meta?,error_text?,encoding?)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT meta (#PCDATA)>
<!ELEMENT error_text (#PCDATA)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="">
      <name></name>
      <meta></meta>
      <error_text></error_text>
      <encoding> iso-8859-1 </encoding>
    </lang>
    <lang id="Romana">
      <name> Română </name>
      <meta> a:8:{s:6:"active";s:1:"0";s:10:"is_default";b:0;s:5:"theme";N;s:11:"date_format";s:8:"%Y-%m-%d";s:17:"decimal_separator";s:1:".";s:19:"thousands_separator";s:1:",";s:8:"decimals";s:1:"2";s:11:"rightToLeft";s:1:"0";} </meta>
      <error_text></error_text>
      <encoding> utf-8 </encoding>
    </lang>
  </languages>
  <pages>
    <page key="PhrasesInTemplates">
      <string key="Job Search">
        <tr lang="Romana"> Cauta Job </tr>
      </string>
      <string key="Find">
        <tr lang="Romana"> Cautare </tr>
      </string>
      <string key="Advanced search">
        <tr lang="Romana"> Cautare avansata </tr>
      </string>
      <string key="Home">
        <tr lang="Romana"> Acasa </tr>
      </string>
      <string key="Register">
        <tr lang="Romana"> Inregistrare </tr>
      </string>
      <string key="Sign In">
        <tr lang="Romana"> Login </tr>
      </string>
      <string key="My Account">
        <tr lang="Romana"> Contul Meu </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="Romana"> Cauta Joburi </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="Romana"> Adauga CV </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="Romana"> Cauta CV-uri </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="Romana"> Adauga Job </tr>
      </string>
      <string key="Contact">
        <tr lang="Romana"> Contact </tr>
      </string>
      <string key="Choose language">
        <tr lang="Romana"> Alege Limba </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="Romana"> Joburi dupa Categorii </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="Romana"> Joburi dupa Orase </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="Romana"> Joburi Premium </tr>
      </string>
      <string key="Employers">
        <tr lang="Romana"> Companii </tr>
      </string>
      <string key="Post a job">
        <tr lang="Romana"> Adauga Job </tr>
      </string>
      <string key="Search resumes">
        <tr lang="Romana"> Cauta CV-uri </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="Romana"> Candidati </tr>
      </string>
      <string key="Post resumes">
        <tr lang="Romana"> Adauga CV </tr>
      </string>
      <string key="Find jobs">
        <tr lang="Romana"> Cauta Joburi </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="Romana"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="Romana"> Ultimele Joburi </tr>
      </string>
      <string key="powered by">
        <tr lang="Romana"> relizat de </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="Romana"> Pastreaza-ma logat </tr>
      </string>
      <string key="Login">
        <tr lang="Romana"> Intra in cont </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="Romana"> Ai uitat parola ? </tr>
      </string>
      <string key="Registration">
        <tr lang="Romana"> Inregistrare </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="Romana"> Nume si Prenume </tr>
      </string>
      <string key="Email">
        <tr lang="Romana"> Email </tr>
      </string>
      <string key="Comments">
        <tr lang="Romana"> Comentarii </tr>
      </string>
      <string key="Please, enter your username in the field below and we\&apos;ll send you a link to a page where you can change your password">
        <tr lang="Romana">  </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="Romana"> Va rugam sa selectati  un grup de utilizatori </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="Romana"> Confirma parola </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="Romana"> Te-ai inregistrat cu succes pe siteul nostru </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="Romana"> Adauga un Nou Anunt </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="Romana"> Nume de utilizator gresit </tr>
      </string>
      <string key="The system cannot proceed as Listing ID not specified">
        <tr lang="Romana"> Sistemul nu poate procesa deoarece ID-ul nu a fost specificat </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="Romana"> ID-ul de plata este invalid </tr>
      </string>
      <string key="No such user">
        <tr lang="Romana"> Nu exista un astfel de utilizator </tr>
      </string>
      <string key="Search">
        <tr lang="Romana"> Cauta </tr>
      </string>
      <string key="No logged in user found">
        <tr lang="Romana"> Nici un utilizator gasit </tr>
      </string>
      <string key="My Jobs">
        <tr lang="Romana"> Joburile Mele </tr>
      </string>
      <string key="My Profile">
        <tr lang="Romana"> Profilul Meu </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="Romana"> Cautari Salvate </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="Romana"> Joburi Salvate </tr>
      </string>
      <string key="Subscriptions">
        <tr lang="Romana"> Abonamente </tr>
      </string>
      <string key="My Notifications">
        <tr lang="Romana"> Notificarile Mele </tr>
      </string>
      <string key="Billing History">
        <tr lang="Romana"> Istoric Plati </tr>
      </string>
      <string key="Logout">
        <tr lang="Romana"> Iesire </tr>
      </string>
      <string key="My Listings">
        <tr lang="Romana"> Anunturile mele </tr>
      </string>
      <string key="Filter">
        <tr lang="Romana"> Filtru </tr>
      </string>
      <string key="Choose subscription">
        <tr lang="Romana"> Alege Abonament </tr>
      </string>
      <string key="unlimited">
        <tr lang="Romana"> nelimitat </tr>
      </string>
      <string key="Next">
        <tr lang="Romana"> Urmatorul </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="Romana"> Editeaza Anunt </tr>
      </string>
      <string key="Edit Pictures">
        <tr lang="Romana"> Editeaza poza </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="Romana"> Upgrade la Joburi Premium </tr>
      </string>
      <string key="You have successfully changed your membership plan">
        <tr lang="Romana"> Ati schimbat cu succes planul de membru </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="Romana"> Sunteti deja abonat </tr>
      </string>
      <string key="You do not have permissions to post  listings.">
        <tr lang="Romana"> Nu aveti permisiunea sa adaugati anunturi </tr>
      </string>
      <string key="No listings found.">
        <tr lang="Romana"> Nici un anunt gasit. </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="Romana"> Id-ul anuntului nu este definit </tr>
      </string>
      <string key="Save">
        <tr lang="Romana"> Salveaza </tr>
      </string>
      <string key="image format is not supported">
        <tr lang="Romana"> Formatul imaginii nu este acceptat </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="Romana"> Ai schimbat cu succes informatiile din profil ! </tr>
      </string>
      <string key="Delete">
        <tr lang="Romana"> Sterge </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="Romana"> Fisier sters cu succes </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="Romana"> Inapoi la editare profil </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="Romana"> Inca nu ati salvat nici o cautare </tr>
      </string>
      <string key="ID">
        <tr lang="Romana"> ID </tr>
      </string>
      <string key="Period">
        <tr lang="Romana"> Perioada </tr>
      </string>
      <string key="State">
        <tr lang="Romana"> Stat </tr>
      </string>
      <string key="from">
        <tr lang="Romana"> de la </tr>
      </string>
      <string key="to">
        <tr lang="Romana"> pentru </tr>
      </string>
      <string key="Date">
        <tr lang="Romana"> Data </tr>
      </string>
      <string key="Description">
        <tr lang="Romana"> Descriere </tr>
      </string>
      <string key="Amount">
        <tr lang="Romana"> Suma </tr>
      </string>
      <string key="Action">
        <tr lang="Romana"> Actiune </tr>
      </string>
      <string key="Total Amount">
        <tr lang="Romana"> Total Suma </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="Romana"> Nu exista nici un anunt salvat </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="Romana"> Notificare cand anuntul este activat </tr>
      </string>
      <string key="Notify on Listing Expiration">
        <tr lang="Romana"> Notificare cand anuntul expira </tr>
      </string>
      <string key="Notify on Contract Expiration">
        <tr lang="Romana"> Notificare cand contractul expira </tr>
      </string>
      <string key="Modify search">
        <tr lang="Romana"> Schimba cautarea </tr>
      </string>
      <string key="Save this search">
        <tr lang="Romana"> Salveaza cautare </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="Romana"> Joburi salvate </tr>
      </string>
      <string key="Saved searches">
        <tr lang="Romana"> Cautari salvate </tr>
      </string>
      <string key="Results: {$listings_number} Jobs">
        <tr lang="Romana"> Rezultate: {$listings_number} Joburi </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="Romana"> Numarul joburilor pe pagina </tr>
      </string>
      <string key="Previous">
        <tr lang="Romana"> Anterior </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="Romana"> Salveaza-ti cautarea </tr>
      </string>
      <string key="Search Name">
        <tr lang="Romana"> Nume Cautare </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="Romana"> Cautarea dvs a fost salvata </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="Romana"> Puteti inchide fereastra acum </tr>
      </string>
      <string key="Save ad">
        <tr lang="Romana"> Salveaza anuntul </tr>
      </string>
      <string key="View job details">
        <tr lang="Romana"> Vezi detalii job </tr>
      </string>
      <string key="Rate this job">
        <tr lang="Romana"> Voteaza acest job </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="Romana"> Va rugam,votati ! </tr>
      </string>
      <string key="Watch a video">
        <tr lang="Romana"> Vezi video </tr>
      </string>
      <string key="Save this Job">
        <tr lang="Romana"> Salveaza job </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="Romana"> Joburi salvate </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="Romana"> Spune unui prieten </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="Romana"> Printeaza anunt </tr>
      </string>
      <string key="View Map">
        <tr lang="Romana"> Vezi Harta </tr>
      </string>
      <string key="Back to Results">
        <tr lang="Romana"> Inapoi la rezultate </tr>
      </string>
      <string key="Modify Search">
        <tr lang="Romana"> Schimba Cautarea </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="Romana"> Voteaza Acest Job </tr>
      </string>
      <string key="User Info">
        <tr lang="Romana"> Info Utilizator </tr>
      </string>
      <string key="All jobs by this company">
        <tr lang="Romana"> Toate joburile acestei companii </tr>
      </string>
      <string key="Video">
        <tr lang="Romana"> Video </tr>
      </string>
      <string key="Photos">
        <tr lang="Romana"> Poze </tr>
      </string>
      <string key="Apply now">
        <tr lang="Romana"> Aplica pentru job </tr>
      </string>
      <string key="Location">
        <tr lang="Romana"> Locatie </tr>
      </string>
      <string key="Please, wait ...">
        <tr lang="Romana"> Va rugam asteptati ... </tr>
      </string>
      <string key="Add your comment">
        <tr lang="Romana"> Adauga comentariu </tr>
      </string>
      <string key="Add">
        <tr lang="Romana"> Adauga </tr>
      </string>
      <string key="Listing has been saved">
        <tr lang="Romana"> Anuntul a fost salvat </tr>
      </string>
      <string key="View details">
        <tr lang="Romana"> Vezi detalii </tr>
      </string>
      <string key="Recommend listing with ID">
        <tr lang="Romana"> Anunt recomandat cu ID </tr>
      </string>
      <string key="Your name">
        <tr lang="Romana"> Numele dvs </tr>
      </string>
      <string key="Your friend\&apos;s name">
        <tr lang="Romana">  </tr>
      </string>
      <string key="Your friend\&apos;s e-mail address">
        <tr lang="Romana">  </tr>
      </string>
      <string key="Your comment (will be send with the recomendation)">
        <tr lang="Romana"> Comentariul ( o sa fie trimis  cu recomandarea ) </tr>
      </string>
      <string key="Send">
        <tr lang="Romana"> Trimite </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="Romana"> Nu se poate trimite </tr>
      </string>
      <string key="Company Info">
        <tr lang="Romana"> Informatii despre Companie </tr>
      </string>
      <string key="You\&apos;ve already voted">
        <tr lang="Romana">  </tr>
      </string>
      <string key="Author">
        <tr lang="Romana"> Autor </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="Romana"> E-mailul dvs </tr>
      </string>
      <string key="Your request">
        <tr lang="Romana"> Cererea dvs </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="Romana"> Atasati CV-ul </tr>
      </string>
      <string key="Cannot send your message">
        <tr lang="Romana"> Mesajul nu se poate trimite </tr>
      </string>
      <string key="You do not have permissions to post Resume listings.">
        <tr lang="Romana"> Nu aveti permisiunea pentru a adauga CV </tr>
      </string>
      <string key="Results: {$listings_number} Resumes">
        <tr lang="Romana"> Rezultate: {$listings_number} CV-uri </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="Romana"> Numarul de CV-uri pe pagina </tr>
      </string>
      <string key="Enter Your Ad Information">
        <tr lang="Romana"> Introduceti informatii despre anuntul dvs </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="Romana"> Adaugati poze </tr>
      </string>
      <string key="is empty">
        <tr lang="Romana"> este gol </tr>
      </string>
      <string key="could not convert video file">
        <tr lang="Romana"> nu se poate face conversia fisierului video </tr>
      </string>
      <string key="is unknown">
        <tr lang="Romana"> este necunoscut </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="Romana"> Administrare Anunturi </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="Romana"> Previzualizare Anunt </tr>
      </string>
      <string key="Manage Listing Pictures">
        <tr lang="Romana"> Administrare poze anunt </tr>
      </string>
      <string key="Go to Manage Listing">
        <tr lang="Romana"> Mergi la administrare anunt </tr>
      </string>
      <string key="Add Picture">
        <tr lang="Romana"> Adauga Poza </tr>
      </string>
      <string key="Caption">
        <tr lang="Romana"> Legenda </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="Romana"> Imagine redusa </tr>
      </string>
      <string key="Actions">
        <tr lang="Romana"> Actiuni </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="Romana"> Sunteti sigur ? </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="Romana"> Editeaza poza </tr>
      </string>
      <string key="Picture">
        <tr lang="Romana"> Poza </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="Romana"> Va rugam sa specificati o adresa de email valida. </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="Romana"> Va rugam sa introduceti numele complet </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="Romana"> Va rugam sa introduceti comentariile dvs. </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="Romana"> Va multumim pentru mesaj.Va vom raspunde in cel mai scurt timp posibil. </tr>
      </string>
      <string key="Invalid password">
        <tr lang="Romana"> Parola invalida </tr>
      </string>
      <string key="Login error">
        <tr lang="Romana"> Parola sau numele de utilizator introduse gresit </tr>
      </string>
      <string key="Browse by category">
        <tr lang="Romana"> Joburi pe categorii </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="Romana"> Nu exista nici un anunt dupa criteriile de cautare. </tr>
      </string>
      <string key="Browse by city">
        <tr lang="Romana"> Cautare dupa oras </tr>
      </string>
      <string key="My Resumes">
        <tr lang="Romana"> Anunturile Mele </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="Romana"> Joburi Salvate </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="Romana"> Alerte Joburi </tr>
      </string>
      <string key="Jobs by {$companyName}">
        <tr lang="Romana"> Joburi de catre {$companyName} </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="Romana"> $select_box_field_distance de Cod Postal $input_text_field_location </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="Romana"> $input_text_field_from pana la $input_text_field_to </tr>
      </string>
      <string key="not confirmed">
        <tr lang="Romana"> nu s-a confirmat </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="Romana"> este folosit deja in sistem </tr>
      </string>
      <string key="Please, enter your username in the field below and we&apos;ll send you a link to a page where you can change your password">
        <tr lang="Romana">  </tr>
      </string>
      <string key="Check all">
        <tr lang="Romana"> Bifeaza tot </tr>
      </string>
      <string key="Uncheck all">
        <tr lang="Romana"> Debifeaza tot </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="Romana"> Actiuni Selectate </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="Romana"> Numarul anunturilor pe pagina </tr>
      </string>
      <string key="Rating">
        <tr lang="Romana"> Voturi </tr>
      </string>
      <string key="Deactivate">
        <tr lang="Romana"> Dezactiveaza </tr>
      </string>
      <string key="Activate">
        <tr lang="Romana"> Activeaza </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="Romana"> Anuntul dvs a fost activat cu succes </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="Romana"> Inapoi la Anunturile Mele </tr>
      </string>
      <string key="Sort by">
        <tr lang="Romana"> Sortare dupa </tr>
      </string>
      <string key="Edit">
        <tr lang="Romana"> Editeaza </tr>
      </string>
      <string key="View Details">
        <tr lang="Romana"> Vezi Detalii </tr>
      </string>
      <string key="Enable Auto notify">
        <tr lang="Romana"> Activeaza notificare automata </tr>
      </string>
      <string key="Disable Auto notify">
        <tr lang="Romana"> Dezactiveaza notificare automata </tr>
      </string>
      <string key="Results: $listings_number Jobs">
        <tr lang="Romana"> Rezultate: $listings_number Joburi </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="Romana"> Joburi de catre $companyName </tr>
      </string>
      <string key="Results: $listings_number Resumes">
        <tr lang="Romana"> Rezultate: $listings_number CV-uri </tr>
      </string>
      <string key="Rate this resume">
        <tr lang="Romana"> Voteaza acest CV </tr>
      </string>
      <string key="View resume details">
        <tr lang="Romana"> Vezi detalii CV </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="Romana"> Toate CV-urile acestui utilizator </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="Romana"> Voteaza Acest CV </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="Romana"> Vezi CV-uri salvate </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="Romana"> Salveaza CV </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="Romana"> CV-uri dupa $firstName $lastName </tr>
      </string>
      <string key="Select a Package">
        <tr lang="Romana"> Selecteaza Pachet </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="Romana"> nu este o valoare intreaga </tr>
      </string>
      <string key="You&apos;ve got a limit of the allowed number of picture">
        <tr lang="Romana"> Ai o limita a numarului de imagini permise </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="Romana"> limita depasita </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="Romana"> Nu aveti permisiunea de a accesa aceasta pagina. </tr>
      </string>
      <string key="Resume search is accessible only for subscribed Employers.">
        <tr lang="Romana"> Cautarea CV-ului este accesibila numai Angajatorilor inscrisi. </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="Romana"> Numele prietenului </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="Romana"> Adresa de e-mail a prietenului </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="Romana"> Stimate client </tr>
      </string>
      <string key="Please make a payment in the amount of $currency_sign $product_info_price for &lt;b&gt;$product_info_name&lt;/b&gt;.">
        <tr lang="Romana"> Va rugam sa faceti o plata in valoare de $currency_sign $product_info_price for &lt;b&gt;$product_info_name&lt;/b&gt;. </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="Romana"> Va rugam sa alegeti una din metodele de plata: </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="Romana"> Transfer Bancar </tr>
      </string>
      <string key="Dear $username, &lt;br /&gt;&lt;br /&gt;Please send us a payment in the amount of $amount for $item_name&lt;br /&gt;Your transaction reference number is $payment_id. &lt;br /&gt;&lt;br /&gt;Thank you!">
        <tr lang="Romana"> Draga $username, &lt;br /&gt;&lt;br /&gt;Va rugam sa ne trimiteti o plata in valoare de $amount pentru $item_name&lt;br /&gt;Numarul de referinta al tranzactiei dvs este $payment_id. &lt;br /&gt;&lt;br /&gt;Va multumim ! </tr>
      </string>
      <string key="There is no listing in the system with the specified ID">
        <tr lang="Romana"> Nu este nici un anunt cu ID-ul specificat </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="Romana"> Informatii Utilizator Anonim </tr>
      </string>
      <string key="Please make a payment in the amount of $currency_sign $product_info_price for">
        <tr lang="Romana"> Va rugam sa faceti o plata in valoare de $currency_sign $product_info_price pentru </tr>
      </string>
      <string key="Welcome">
        <tr lang="Romana"> Bine ai venit </tr>
      </string>
      <string key="Dear $username, &lt;br /&gt;&lt;br /&gt;Please send us a payment in the amount of $amount for">
        <tr lang="Romana"> Draga $username, &lt;br /&gt;&lt;br /&gt;Va rugam sa faceti o plata in valoare de $amount pentru </tr>
      </string>
      <string key="Your transaction reference number is $payment_id. &lt;br /&gt;&lt;br /&gt;Thank you!">
        <tr lang="Romana"> Numarul de referinta al tranzactiei dvs este $payment_id. &lt;br /&gt;&lt;br /&gt;Va multumim ! </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="Romana"> Va rugam sa va autentificati pentru a putea accesa aceasta pagina.Daca nu aveti inca un cont,va rugam sa </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="Romana"> Companii Recomandate </tr>
      </string>
      <string key="Get resumes by email">
        <tr lang="Romana"> Primeste CV-urile in email </tr>
      </string>
      <string key="Get jobs by email">
        <tr lang="Romana"> Primeste Joburile in email </tr>
      </string>
      <string key="Please use the &quot;Control&quot; key to choose two or more options">
        <tr lang="Romana"> Va rugam sa apasati tasta &quot;Ctrl&quot; pentru a alege doua sau mai multe optiuni </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="Romana"> Confirma E-mail </tr>
      </string>
      <string key="Reload Image">
        <tr lang="Romana"> Reincarca Imagine </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="Romana"> Accepta termenii si conditiile </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="Romana"> Citeste termenii si conditiile </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="Romana"> Alerte CV-uri </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="Romana"> Cerere de urmarire </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="Romana"> Alerta Nume CV </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="Romana"> Adauga alerta CV nou </tr>
      </string>
      <string key="Disable">
        <tr lang="Romana"> Dezactiveaza </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="Romana"> Vizualizeaza cautarile </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="Romana"> Adauga alerta CV </tr>
      </string>
      <string key="Alert Name">
        <tr lang="Romana"> Nume Alerta </tr>
      </string>
      <string key="Job Title">
        <tr lang="Romana"> Titlu Job </tr>
      </string>
      <string key="Date Applied">
        <tr lang="Romana"> Data aplicarii </tr>
      </string>
      <string key="Status">
        <tr lang="Romana"> Statut </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="Romana"> CV Atasat </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="Romana"> Numele Candidatului </tr>
      </string>
      <string key="User comments">
        <tr lang="Romana"> Comentariile utilizatorului </tr>
      </string>
      <string key="View Attached File">
        <tr lang="Romana"> Vezi fisier atasat </tr>
      </string>
      <string key="Jobs Search Results">
        <tr lang="Romana"> Joburile rezultate </tr>
      </string>
      <string key="Save this Search / Job Alert">
        <tr lang="Romana"> Salveaza cautare / Alerta Job </tr>
      </string>
      <string key="Company Profile">
        <tr lang="Romana"> Profil Companie </tr>
      </string>
      <string key="Sign in">
        <tr lang="Romana"> Intra in </tr>
      </string>
      <string key="You have no listings now. Click">
        <tr lang="Romana"> Nu aveti nici un anunt acum.Click </tr>
      </string>
      <string key="here">
        <tr lang="Romana"> aici </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="Romana"> pentru a adauga un anunt nou. </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="Romana"> Campurile marcate cu steluta ( </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="Romana"> ) sunt obligatorii </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="Romana"> Va rugam sa va autentificati pentru a adauga un anunt.Daca nu aveti inca un cont,va rugam sa va </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="Romana"> in mai putin $radius $radius_search_unit de $location </tr>
      </string>