<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (name?,meta?,error_text?,encoding?)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT meta (#PCDATA)>
<!ELEMENT error_text (#PCDATA)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="ru">
      <name> Русский </name>
      <meta> a:8:{s:6:"active";s:1:"0";s:10:"is_default";b:0;s:5:"theme";s:0:"";s:11:"date_format";s:8:"%d.%m.%Y";s:17:"decimal_separator";s:1:".";s:19:"thousands_separator";s:1:",";s:8:"decimals";s:1:"1";s:11:"rightToLeft";s:1:"0";} </meta>
      <error_text></error_text>
      <encoding> utf-8 </encoding>
    </lang>
  </languages>
  <pages>
    <page key="PhrasesInTemplates">
      <string key="About Us">
        <tr lang="ru"> О нас </tr>
      </string>
      <string key="Auto News">
        <tr lang="ru"> Авто новости </tr>
      </string>
      <string key="Service Providers">
        <tr lang="ru"> Поставщики услуг </tr>
      </string>
      <string key="Sign in">
        <tr lang="ru"> Войти </tr>
      </string>
      <string key="Register">
        <tr lang="ru"> Регистрация </tr>
      </string>
      <string key="Saved Ads">
        <tr lang="ru"> Сохраненные объяв. </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="ru"> Сохраненные поиски </tr>
      </string>
      <string key="Log Out">
        <tr lang="ru"> Выйти </tr>
      </string>
      <string key="My Listings">
        <tr lang="ru"> Мои объявления </tr>
      </string>
      <string key="My Notifications">
        <tr lang="ru"> Мои уведомления </tr>
      </string>
      <string key="My Payments">
        <tr lang="ru"> Мои платежи </tr>
      </string>
      <string key="My Profile">
        <tr lang="ru"> Мой профиль </tr>
      </string>
      <string key="Find Your Car">
        <tr lang="ru"> Найти авто </tr>
      </string>
      <string key="Sell Your Car">
        <tr lang="ru"> Продать авто </tr>
      </string>
      <string key="Home">
        <tr lang="ru"> Главная </tr>
      </string>
      <string key="Contact Us">
        <tr lang="ru"> Контакт </tr>
      </string>
      <string key="Advanced search">
        <tr lang="ru"> Расширенный поиск </tr>
      </string>
      <string key="Automobile classifieds demo site">
        <tr lang="ru"> Демо сайт авто объявлений </tr>
      </string>
      <string key="Show Results">
        <tr lang="ru"> Результаты </tr>
      </string>
      <string key="CARS BY MAKE">
        <tr lang="ru"> Авто по маркам </tr>
      </string>
      <string key="CARS BY BODY STYLE">
        <tr lang="ru"> Авто по типу кузова </tr>
      </string>
      <string key="You are logged in already">
        <tr lang="ru"> Вы уже вошли в систему </tr>
      </string>
      <string key="Please select the appropriate user group:">
        <tr lang="ru"> Пажалуйста, выберите группу пользователя: </tr>
      </string>
      <string key="Select a Package">
        <tr lang="ru"> Выберите пакет </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="ru"> Ваше объявление успешно активировано </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="ru"> Вернуться к моему списку </tr>
      </string>
      <string key="Features">
        <tr lang="ru"> Опции </tr>
      </string>
      <string key="Number of listings per page:">
        <tr lang="ru"> Объявлений на странице: </tr>
      </string>
      <string key="Previous">
        <tr lang="ru"> Пред. </tr>
      </string>
      <string key="Next">
        <tr lang="ru"> След. </tr>
      </string>
      <string key="FIND YOUR CAR">
        <tr lang="ru"> Найти авто </tr>
      </string>
      <string key="Check all">
        <tr lang="ru"> Выделить все </tr>
      </string>
      <string key="Results: $listings_number Listings">
        <tr lang="ru"> Найдено объявлений: $listings_number </tr>
      </string>
      <string key="Browse by Make Model">
        <tr lang="ru"> Обзор по маркам и моделям </tr>
      </string>
      <string key="Choose language">
        <tr lang="ru"> Выбрать язык </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="ru"> $select_box_field_distance Индекс $input_text_field_location </tr>
      </string>
      <string key="Featured Vehicles">
        <tr lang="ru"> Горячие объявления </tr>
      </string>
      <string key="Sign In">
        <tr lang="ru"> Войти </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="ru"> Запомнить меня </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="ru"> Забыли пароль? </tr>
      </string>
      <string key="Registration">
        <tr lang="ru"> Регистрация </tr>
      </string>
      <string key="Welcome">
        <tr lang="ru"> Добро Пожаловать, </tr>
      </string>
      <string key="Add Listing">
        <tr lang="ru"> Добавить объявление </tr>
      </string>
      <string key="Enter Your Ad Information">
        <tr lang="ru"> Введите информацию о Вашем объявлении </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="ru"> Действия с объявлением </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="ru"> Предварительный просмотр </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="ru"> Редактировать объявление </tr>
      </string>
      <string key="Pay For Listing">
        <tr lang="ru"> Произвести оплату </tr>
      </string>
      <string key="Save Ad">
        <tr lang="ru"> Сохранить объяв. </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="ru"> Отправить другу </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="ru"> Печать </tr>
      </string>
      <string key="Get Directions">
        <tr lang="ru"> Схема проезда </tr>
      </string>
      <string key="Loan Calculator">
        <tr lang="ru"> Расчет кредита </tr>
      </string>
      <string key="Your name">
        <tr lang="ru"> Ваше имя </tr>
      </string>
      <string key="Recommend listing with ID">
        <tr lang="ru"> Рекомендация объявления № </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="ru"> Имя друга </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="ru"> E-mail друга </tr>
      </string>
      <string key="Your comment (will be send with the recommendation)">
        <tr lang="ru"> Ваши комментарии </tr>
      </string>
      <string key="Car details">
        <tr lang="ru"> Детали авто </tr>
      </string>
      <string key="Features:">
        <tr lang="ru"> Опции: </tr>
      </string>
      <string key="Seller Info">
        <tr lang="ru"> Информация о продавце </tr>
      </string>
      <string key="Contact seller">
        <tr lang="ru"> Связаться с продавцом </tr>
      </string>
      <string key="All ads by this seller">
        <tr lang="ru"> Все объявления этого пользователя </tr>
      </string>
      <string key="Monthly Payment">
        <tr lang="ru"> Месячная выплата </tr>
      </string>
      <string key="Loan Amount">
        <tr lang="ru"> Размер кредита </tr>
      </string>
      <string key="Term of Loan">
        <tr lang="ru"> Срок кредита </tr>
      </string>
      <string key="months">
        <tr lang="ru"> месяцев </tr>
      </string>
      <string key="Interest Rate">
        <tr lang="ru"> Процентная ставка </tr>
      </string>
      <string key="$select_box_field_from to $select_box_field_to">
        <tr lang="ru"> $select_box_field_from - $select_box_field_to </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="ru"> $input_text_field_from - $input_text_field_to </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="ru"> Подтвердите пароль </tr>
      </string>
      <string key="Uncheck all">
        <tr lang="ru"> Снять все выделения </tr>
      </string>
      <string key="Sort by:">
        <tr lang="ru"> Сортировка: </tr>
      </string>
      <string key="View Details">
        <tr lang="ru"> Детали </tr>
      </string>
      <string key="Deactivate Listing">
        <tr lang="ru"> Деактивировать </tr>
      </string>
      <string key="Delete Listing">
        <tr lang="ru"> Удалить </tr>
      </string>
      <string key="Back to Results">
        <tr lang="ru"> Вернуться к результатам </tr>
      </string>
      <string key="Modify Search">
        <tr lang="ru"> Изменить поиск </tr>
      </string>
      <string key="View the CARFAX Vehicle History Report">
        <tr lang="ru"> История авто от CARFAX </tr>
      </string>
      <string key="Save this Search">
        <tr lang="ru"> Сохранить поиск </tr>
      </string>
      <string key="Save ad">
        <tr lang="ru"> Сохранить объявление </tr>
      </string>
      <string key="View car details">
        <tr lang="ru"> Детали </tr>
      </string>
      <string key="Edit Pictures">
        <tr lang="ru"> Редактировать фото </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="ru"> Неверное имя пользователя </tr>
      </string>
      <string key="Please, enter your username in the field below and we&apos;ll send you a link to a page where you can change your password">
        <tr lang="ru"> Пожалуйста, введите Ваш логин в поле ниже - и мы вышлем Вам ссылку для восстановления пароля на e-mail, указанный при регистрации </tr>
      </string>
      <string key="The message was sent successfully">
        <tr lang="ru"> Сообщение успешно отправлено </tr>
      </string>
      <string key="Action">
        <tr lang="ru"> Действия </tr>
      </string>
      <string key="Total Amount">
        <tr lang="ru"> Итого </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="ru"> Не указан № объявления </tr>
      </string>
      <string key="There is no listing in the system with the specified ID">
        <tr lang="ru"> Не найденно объявление с указанным ID </tr>
      </string>
      <string key="Listing with specified ID is not active">
        <tr lang="ru"> Объявление с указанным номером не активно </tr>
      </string>
      <string key="There are no articles available at this time">
        <tr lang="ru"> На данный момент статей нет </tr>
      </string>
      <string key="Business Catalog">
        <tr lang="ru"> Бизнес каталог </tr>
      </string>
      <string key="view full profile">
        <tr lang="ru"> Подробная информация </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="ru"> Сохраненные объявления </tr>
      </string>
      <string key="Delete">
        <tr lang="ru"> Удалить </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="ru"> Нет сохраненных объявлений </tr>
      </string>
      <string key="Payment is not verified">
        <tr lang="ru"> Платеж не прошел проверку </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="ru"> Неверный номер платежа </tr>
      </string>
      <string key="You have successfully subscribed for the membership plan">
        <tr lang="ru"> Вы успешно подписаны </tr>
      </string>
      <string key="Your name:">
        <tr lang="ru"> Ваше имя: </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="ru"> Ваш e-mail </tr>
      </string>
      <string key="Your request">
        <tr lang="ru"> Текст сообщения </tr>
      </string>
      <string key="Inquiry for listing with ID">
        <tr lang="ru"> Запрос по объявлению № </tr>
      </string>
      <string key="Your letter was sent">
        <tr lang="ru"> Сообщение отправлено </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="ru"> Сообщение не может быть отправлено </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="ru"> Вы не сохранили ни одного поиска </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="ru"> Сохранить поиск </tr>
      </string>
      <string key="Search Name">
        <tr lang="ru"> Название поиска </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="ru"> В системе нет объявлений с указанными параметрами </tr>
      </string>
      <string key="The system cannot proceed as Listing ID not specified">
        <tr lang="ru"> Не указан номер объявления </tr>
      </string>
      <string key="Wrong Listing ID specified">
        <tr lang="ru"> Неверный номер объявления </tr>
      </string>
      <string key="Payment already has been processed">
        <tr lang="ru"> Платеж уже осуществлен </tr>
      </string>
      <string key="Invalid listing ID is specified">
        <tr lang="ru"> Неверный номер объявления </tr>
      </string>
      <string key="Listing is already featured">
        <tr lang="ru"> У объявления уже установлен этот статус </tr>
      </string>
      <string key="The system cannot proceed as some key parameters are missed">
        <tr lang="ru"> Не указаны ключевые параметры </tr>
      </string>
      <string key="Your listing succesfully upgraded to featured">
        <tr lang="ru"> Объявление успешно переведено в статус &quot;Горячие&quot; </tr>
      </string>
      <string key="The key parameters are not specified">
        <tr lang="ru"> Не указаны ключевые параметры </tr>
      </string>
      <string key="Wrong parameters are specified">
        <tr lang="ru"> Указаны неверные параметры </tr>
      </string>
      <string key="You are not owner of this listing">
        <tr lang="ru"> Вы не являетесь владельцем этого объявления </tr>
      </string>
      <string key="Listing has been saved">
        <tr lang="ru"> Объявление сохранено </tr>
      </string>
      <string key="Listing ID not specified">
        <tr lang="ru"> Не указан номер объявления </tr>
      </string>
      <string key="Maximum query storage capacity exceeded for you as an unregistered user. To save more searches, please login or register.">
        <tr lang="ru"> Вы исчерпали место для не зарегистрированного пользователя. Для сохранения большего количества поисков, Вам необходимо зарегистрироваться. </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="ru"> Поиск сохранен </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="ru"> Можете закрыть это окно </tr>
      </string>
      <string key="Disable Auto notify">
        <tr lang="ru"> выкл. Авто уведомление </tr>
      </string>
      <string key="Enable Auto notify">
        <tr lang="ru"> вкл. Авто уведомление </tr>
      </string>
      <string key="Your listing was successfully added to the system!">
        <tr lang="ru"> Ваше объявление успешно добавлено! </tr>
      </string>
      <string key="You&apos;ve got the limit of the number of the active listings">
        <tr lang="ru"> Вы достигли предела по количеству активных объявлений </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="ru"> Добавить новое объявление </tr>
      </string>
      <string key="There&apos;s no listing packages available on your membership plan">
        <tr lang="ru"> Для вашего плана не настроено ни одного пакета </tr>
      </string>
      <string key="You&apos;ve reached the limit of number of listings alowed by your plan">
        <tr lang="ru"> Вы достигли предела по кол. объявлений </tr>
      </string>
      <string key="Choose your memberhsip plan">
        <tr lang="ru"> Выберете Ваш план </tr>
      </string>
      <string key="The service was not executed, contact to administrator of the site.">
        <tr lang="ru"> Услуга не выполнена. Обратитесь к администратору сайта. </tr>
      </string>
      <string key="This service is not available for you.">
        <tr lang="ru"> Эта услуга вам не доступна. </tr>
      </string>
      <string key="This service is not found.">
        <tr lang="ru"> Услуга не найдена. </tr>
      </string>
      <string key="You are not logged in">
        <tr lang="ru"> Вы не вошли в систему </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="ru"> Вы уже подписаны </tr>
      </string>
      <string key="There is no such membership plan in your group">
        <tr lang="ru"> Ваша группа пользователей не включает этот план </tr>
      </string>
      <string key="Cannot save your membership plan">
        <tr lang="ru"> Не удалось сохранить план </tr>
      </string>
      <string key="Choose subscription">
        <tr lang="ru"> Выбор подписки </tr>
      </string>
      <string key="Please specify a valid email address.Please provide your full name.">
        <tr lang="ru"> Пажалуйста, укажите действительный email. </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="ru"> Ваше имя </tr>
      </string>
      <string key="Email">
        <tr lang="ru"> Email </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="ru"> Спасибо за Ваше сообщение. Мы ответим в ближайшее время. </tr>
      </string>
      <string key="Manage Listing Pictures">
        <tr lang="ru"> Редактировать фото </tr>
      </string>
      <string key="Go to Manage Listing">
        <tr lang="ru"> Перейти к действиям с объявлением </tr>
      </string>
      <string key="Add Picture">
        <tr lang="ru"> Добавить фото </tr>
      </string>
      <string key="Caption">
        <tr lang="ru"> Заголовок </tr>
      </string>
      <string key="Picture">
        <tr lang="ru"> Фото </tr>
      </string>
      <string key="You&apos;ve got a limit of the allowed number of picture">
        <tr lang="ru"> Вы превысили лимит загружаемых фотографий </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="ru"> Иконка </tr>
      </string>
      <string key="Actions">
        <tr lang="ru"> Действия </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="ru"> Редактировать фото </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="ru"> Комментарии </tr>
      </string>
      <string key="Online Poll Results">
        <tr lang="ru"> Результаты голосования </tr>
      </string>
      <string key="votes">
        <tr lang="ru"> голосов </tr>
      </string>
      <string key="Total votes">
        <tr lang="ru"> Итого голосов </tr>
      </string>
      <string key="No votes available at this time">
        <tr lang="ru"> Нет ни одного голоса </tr>
      </string>
      <string key="Publications">
        <tr lang="ru"> Публикации </tr>
      </string>
      <string key="Section list">
        <tr lang="ru"> Список секций </tr>
      </string>
      <string key="There no categories available at this time">
        <tr lang="ru"> Нет категорий </tr>
      </string>
      <string key="The system cannot proceed as some key parameters are missing">
        <tr lang="ru"> Не указанны ключевые параметры </tr>
      </string>
      <string key="No such user found">
        <tr lang="ru"> Пользователь не найден </tr>
      </string>
      <string key="Wrong activation key is specified">
        <tr lang="ru"> Не верный ключ активации </tr>
      </string>
      <string key="Cannot activate account. Please contact administrator.">
        <tr lang="ru"> Не удалось активировать учетную запись. Обратитесь к администратору. </tr>
      </string>
      <string key="Username is empty">
        <tr lang="ru"> Не указано имя пользователя </tr>
      </string>
      <string key="Verification key is empty">
        <tr lang="ru"> Не указан ключ верификации </tr>
      </string>
      <string key="Worng verification key is specified">
        <tr lang="ru"> Не верный ключ верификации </tr>
      </string>
      <string key="Password is not confirmed or empty">
        <tr lang="ru"> Пароль не подтвержден или пустой </tr>
      </string>
      <string key="Wrong parameters specified">
        <tr lang="ru"> Указанны неверные параметры </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="ru"> Файл успешно удален </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="ru"> Вернуться к редактированию профиля </tr>
      </string>
      <string key="No such user">
        <tr lang="ru"> Такого пользователя не существует </tr>
      </string>
      <string key="Invalid password">
        <tr lang="ru"> Неверный пароль </tr>
      </string>
      <string key="Login error">
        <tr lang="ru"> Неправильное имя пользователя и/или пароль </tr>
      </string>
      <string key="Your account is not active">
        <tr lang="ru"> Ваша учетная запись не активна </tr>
      </string>
      <string key="Your registration is almost complete. Please check your mailbox for an activation email containing further instructions.">
        <tr lang="ru"> Вам выслано письмо активации. Для завершения регистрации следуйте инструкциям в письме. </tr>
      </string>
      <string key="Failed to send activation email.">
        <tr lang="ru"> Не удалось отправить письмо активации. </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="ru"> Регистрация успешно завершена </tr>
      </string>
      <string key="Your password was successfully changed">
        <tr lang="ru"> Смена пароля успешно произведена </tr>
      </string>
      <string key="Cannot set this membership plan for your account">
        <tr lang="ru"> Не удалось установить выбранный план для вашей учетной записи </tr>
      </string>
      <string key="User not logged in">
        <tr lang="ru"> Пользователь не залогинен </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="ru"> Уведомлять об активации объявлений </tr>
      </string>
      <string key="Notify on Listing Expiration">
        <tr lang="ru"> Уведомлять об истечении срока действия объявлений </tr>
      </string>
      <string key="Notify on Contract Expiration">
        <tr lang="ru"> Уведомлять об истечении подписки </tr>
      </string>
      <string key="Watch a video">
        <tr lang="ru"> Просмотр видео </tr>
      </string>
      <string key="Send">
        <tr lang="ru"> Отправить </tr>
      </string>
      <string key="Save">
        <tr lang="ru"> Сохранить </tr>
      </string>
      <string key="Add">
        <tr lang="ru"> Добавить </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="ru"> Добавить фото </tr>
      </string>
      <string key="Next &gt;&gt;">
        <tr lang="ru"> След. &gt;&gt; </tr>
      </string>
      <string key="Deactivate">
        <tr lang="ru"> Деактивировать </tr>
      </string>
      <string key="Filter">
        <tr lang="ru"> Фильтровать </tr>
      </string>
      <string key="Find">
        <tr lang="ru"> Поиск </tr>
      </string>
      <string key="Go search">
        <tr lang="ru"> Искать </tr>
      </string>
      <string key="Search">
        <tr lang="ru"> Поиск </tr>
      </string>
      <string key="Submit">
        <tr lang="ru"> Отправить </tr>
      </string>
      <string key="Vote">
        <tr lang="ru"> Голосовать </tr>
      </string>
      <string key="Login">
        <tr lang="ru"> Войти </tr>
      </string>
      <string key="Subscription">
        <tr lang="ru"> Подписка </tr>
      </string>
      <string key="Account Activation">
        <tr lang="ru"> Активация профиля </tr>
      </string>
      <string key="Fields marked &lt;font color=&quot;red&quot;&gt;*&lt;/font&gt; are required">
        <tr lang="ru"> &lt;font color=&quot;red&quot;&gt;*&lt;/font&gt; - обязательные поля </tr>
      </string>
      <string key="file not specified">
        <tr lang="ru"> не указан файл </tr>
      </string>
      <string key="not supported image format">
        <tr lang="ru"> данный формат не поддерживается </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="ru"> Ваш лимит исчерпан </tr>
      </string>
      <string key="is empty">
        <tr lang="ru"> пустой </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="ru"> это значение уже используется в системе </tr>
      </string>
      <string key="not confirmed">
        <tr lang="ru"> не подтверждено </tr>
      </string>
      <string key="length is exceeded">
        <tr lang="ru"> превышенна длина </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="ru"> это не целое число </tr>
      </string>
      <string key="value is out of range">
        <tr lang="ru"> значение за пределами возможных значений </tr>
      </string>
      <string key="is not an float value">
        <tr lang="ru"> указанное значение не является числом </tr>
      </string>
      <string key="is unknown">
        <tr lang="ru"> неизвестно </tr>
      </string>
      <string key="is not valid">
        <tr lang="ru"> не действительно </tr>
      </string>
      <string key="this file is not in a supported video file format">
        <tr lang="ru"> формат видео файла не поддерживается </tr>
      </string>
      <string key="filesize exceeds the quota">
        <tr lang="ru"> размер файла превышает допустимое значение </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="ru"> within $radius $radius_search_unit of $location </tr>
      </string>
      <string key="miles">
        <tr lang="ru"> миль </tr>
      </string>
      <string key="Listings by $firstName $lastName">
        <tr lang="ru"> Объявления пользователя $firstName $lastName </tr>
      </string>
      <string key="Account activated. Please &lt;a href=&quot;$url&quot;&gt;login&lt;/a&gt;.">
        <tr lang="ru"> Профиль активирован. Пожалуйста &lt;a href=&quot;$url&quot;&gt;войдите в систему&lt;/a&gt;. </tr>
      </string>
      <string key="Dear $username, &lt;br /&gt;&lt;br /&gt;Please send us a payment in the amount of $amount for $item_name&lt;br /&gt;Your transaction reference number is $payment_id. &lt;br /&gt;&lt;br /&gt;Thank you!">
        <tr lang="ru"> Уважаемый $username,&lt;br /&gt;&lt;br /&gt; Вам необходимо выслать нам сумму в размере $amount за $item_name.&lt;br /&gt; Номер вашей транзакции $payment_id.&lt;br \&gt;&lt;br \&gt; Спасибо </tr>
      </string>
      <string key="Please make a payment in the amount of $currency_sign $product_info_price for &lt;b&gt;$product_info_name&lt;/b&gt;.">
        <tr lang="ru"> Вам необходимо произвести платеж в размере $currency_sign $product_info_price за &lt;b&gt;$product_info_name&lt;/b&gt;. </tr>
      </string>
      <string key="E-mail">
        <tr lang="ru"> E-mail </tr>
      </string>
      <string key="Fax">
        <tr lang="ru"> Факс </tr>
      </string>
      <string key="Website">
        <tr lang="ru"> Веб сайт </tr>
      </string>
      <string key="Phone">
        <tr lang="ru"> Телефон </tr>
      </string>
      <string key="ID">
        <tr lang="ru"> № </tr>
      </string>
      <string key="Period">
        <tr lang="ru"> Период </tr>
      </string>
      <string key="State">
        <tr lang="ru"> Статус </tr>
      </string>
      <string key="from">
        <tr lang="ru"> от </tr>
      </string>
      <string key="to">
        <tr lang="ru"> до </tr>
      </string>
      <string key="Date">
        <tr lang="ru"> Дата </tr>
      </string>
      <string key="Amount">
        <tr lang="ru"> Сумма </tr>
      </string>
      <string key="Complete">
        <tr lang="ru"> Завершить </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="ru"> Установить статус &quot;Горячие&quot; </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="ru"> Выберите подходящую для Вас группу пользователя </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="ru"> Уважаемый клиент, </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="ru"> Пожалуйста, выберите удобный для Вас способ оплаты: </tr>
      </string>
      <string key="Vehicle Option">
        <tr lang="ru"> Опции Автомобиля </tr>
      </string>
      <string key="Safety">
        <tr lang="ru"> Безопасность </tr>
      </string>
      <string key="Comfort">
        <tr lang="ru"> Удобство </tr>
      </string>
      <string key="Seats">
        <tr lang="ru"> Сиденья </tr>
      </string>
      <string key="Other Features">
        <tr lang="ru"> Другие </tr>
      </string>
      <string key="Sound System">
        <tr lang="ru"> Звуковая система </tr>
      </string>
      <string key="Windows">
        <tr lang="ru"> Окна </tr>
      </string>
      <string key="Sort by">
        <tr lang="ru"> Сортировать по </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="ru"> Действие с выделенными </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="ru"> Количество объявлений на странице </tr>
      </string>
      <string key="Description">
        <tr lang="ru"> Описание </tr>
      </string>
      <string key="List of Categories">
        <tr lang="ru"> Список категорий </tr>
      </string>
      <string key="No listings found.">
        <tr lang="ru"> По этому запросу объявлений не найдено </tr>
      </string>
      <string key="Browse by Body Style">
        <tr lang="ru"> Обзор по типу кузова </tr>