<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
<!ELEMENT translation2 (languages,pages)>
<!ELEMENT languages (lang*)>
<!ELEMENT lang (name?,meta?,error_text?,encoding?)>
<!ATTLIST lang id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT meta (#PCDATA)>
<!ELEMENT error_text (#PCDATA)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT pages (page*)>
<!ELEMENT page (string*)>
<!ATTLIST page key CDATA #REQUIRED>
<!ELEMENT string (tr*)>
<!ATTLIST string key CDATA #REQUIRED>
<!ELEMENT tr (#PCDATA)>
<!ATTLIST tr lang IDREF #REQUIRED>
]>

<translation2>
  <languages>
    <lang id="">
      <name></name>
      <meta></meta>
      <error_text></error_text>
      <encoding> iso-8859-1 </encoding>
    </lang>
    <lang id="vi">
      <name> Việt </name>
      <meta> a:8:{s:6:"active";s:1:"1";s:10:"is_default";b:0;s:5:"theme";N;s:11:"date_format";s:8:"%Y-%m-%d";s:17:"decimal_separator";s:0:"";s:19:"thousands_separator";s:1:",";s:8:"decimals";s:1:"0";s:11:"rightToLeft";s:1:"0";} </meta>
      <error_text></error_text>
      <encoding> utf-8 </encoding>
    </lang>
  </languages>
  <pages>
    <page key="PhrasesInTemplates">
      <string key="Job Search">
        <tr lang="vi"> Tìm việc </tr>
      </string>
      <string key="Find">
        <tr lang="vi"> Tìm </tr>
      </string>
      <string key="Advanced search">
        <tr lang="vi"> Tìm kiếm nâng cao </tr>
      </string>
      <string key="Home">
        <tr lang="vi"> Trang chủ </tr>
      </string>
      <string key="Register">
        <tr lang="vi"> Đăng ký </tr>
      </string>
      <string key="Sign In">
        <tr lang="vi"> Đăng nhập </tr>
      </string>
      <string key="My Account">
        <tr lang="vi"> Tài khoản của tôi </tr>
      </string>
      <string key="Find Jobs">
        <tr lang="vi"> Tìm Việc Làm </tr>
      </string>
      <string key="Post Resumes">
        <tr lang="vi"> Đăng Hồ Sơ </tr>
      </string>
      <string key="Search Resumes">
        <tr lang="vi"> Tìm Hồ Sơ </tr>
      </string>
      <string key="Post Jobs">
        <tr lang="vi"> Đăng Tuyển </tr>
      </string>
      <string key="Contact">
        <tr lang="vi"> Liên hệ </tr>
      </string>
      <string key="Choose language">
        <tr lang="vi"> Chọn ngôn ngữ </tr>
      </string>
      <string key="Jobs by Category">
        <tr lang="vi"> Thể loại công việc theo </tr>
      </string>
      <string key="Jobs by City">
        <tr lang="vi"> Việc làm của thành phố </tr>
      </string>
      <string key="Featured Jobs">
        <tr lang="vi"> Các Jobs </tr>
      </string>
      <string key="Employers">
        <tr lang="vi"> Sử dụng lao động </tr>
      </string>
      <string key="Post a job">
        <tr lang="vi"> Đăng một công việc </tr>
      </string>
      <string key="Search resumes">
        <tr lang="vi"> Tìm kiếm hồ sơ </tr>
      </string>
      <string key="Job Seekers">
        <tr lang="vi"> Người tìm việc </tr>
      </string>
      <string key="Post resumes">
        <tr lang="vi"> Đăng hồ sơ </tr>
      </string>
      <string key="Find jobs">
        <tr lang="vi"> Tìm việc làm </tr>
      </string>
      <string key="RSS Feed">
        <tr lang="vi"> RSS Feed </tr>
      </string>
      <string key="Latest Jobs">
        <tr lang="vi"> Công việc mới nhất </tr>
      </string>
      <string key="powered by">
        <tr lang="vi">  </tr>
      </string>
      <string key="Keep me signed in">
        <tr lang="vi"> Hãy giữ cho tôi đăng nhập </tr>
      </string>
      <string key="Login">
        <tr lang="vi"> Đăng nhập </tr>
      </string>
      <string key="Forgot Your Password?">
        <tr lang="vi"> Quên mật khẩu của bạn? </tr>
      </string>
      <string key="Registration">
        <tr lang="vi"> Đăng ký </tr>
      </string>
      <string key="Salutation First and Last Name">
        <tr lang="vi"> Lời chào đầu và cuối Tên </tr>
      </string>
      <string key="Email">
        <tr lang="vi"> Email </tr>
      </string>
      <string key="Comments">
        <tr lang="vi"> Bình luận </tr>
      </string>
      <string key="Submit">
        <tr lang="vi"> Gửi </tr>
      </string>
      <string key="Please, enter your username in the field below and we\&apos;ll send you a link to a page where you can change your password">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please select the appropriate user group">
        <tr lang="vi"> Xin vui lòng chọn nhóm người dùng thích hợp </tr>
      </string>
      <string key="Confirm Password">
        <tr lang="vi"> Xác nhận mật khẩu </tr>
      </string>
      <string key="You have successfully registered in our site">
        <tr lang="vi"> Bạn đã đăng ký vào trang web của chúng tôi </tr>
      </string>
      <string key="Add a New Listing">
        <tr lang="vi"> Thêm một danh mục mới </tr>
      </string>
      <string key="You specified wrong username">
        <tr lang="vi"> sai tên đăng nhập </tr>
      </string>
      <string key="The system cannot proceed as Listing ID not specified">
        <tr lang="vi">  </tr>
      </string>
      <string key="Invalid payment ID is specified">
        <tr lang="vi"> thanh toán xác định không hợp lệ </tr>
      </string>
      <string key="No such user">
        <tr lang="vi"> Không có người dùng như vậy </tr>
      </string>
      <string key="Search">
        <tr lang="vi"> Tìm kiếm </tr>
      </string>
      <string key="No logged in user found">
        <tr lang="vi">  </tr>
      </string>
      <string key="My Jobs">
        <tr lang="vi"> Công việc của tôi </tr>
      </string>
      <string key="My Profile">
        <tr lang="vi"> Hồ sơ của tôi </tr>
      </string>
      <string key="Saved Searches">
        <tr lang="vi"> Tìm kiếm đã lưu </tr>
      </string>
      <string key="Saved Listings">
        <tr lang="vi"> Danh sách đã lưu </tr>
      </string>
      <string key="Subscriptions">
        <tr lang="vi"> Đăng ký </tr>
      </string>
      <string key="My Notifications">
        <tr lang="vi"> Thông báo của tôi </tr>
      </string>
      <string key="Billing History">
        <tr lang="vi"> Thanh toán lịch sử </tr>
      </string>
      <string key="Logout">
        <tr lang="vi"> Thoát </tr>
      </string>
      <string key="My Listings">
        <tr lang="vi"> Danh sách của tôi </tr>
      </string>
      <string key="Filter">
        <tr lang="vi"> Lọc </tr>
      </string>
      <string key="Choose subscription">
        <tr lang="vi"> Chọn đăng ký </tr>
      </string>
      <string key="unlimited">
        <tr lang="vi"> không giới hạn </tr>
      </string>
      <string key="Next">
        <tr lang="vi"> Tiếp theo </tr>
      </string>
      <string key="Edit Listing">
        <tr lang="vi"> Chỉnh sửa danh mục </tr>
      </string>
      <string key="Edit Pictures">
        <tr lang="vi"> Chỉnh sửa hình ảnh </tr>
      </string>
      <string key="Upgrade to Featured">
        <tr lang="vi"> Nâng cấp lên đặc trưng </tr>
      </string>
      <string key="You have successfully changed your membership plan">
        <tr lang="vi"> Bạn có kế hoạch thay đổi thành công thành viên của bạn </tr>
      </string>
      <string key="You have already subscribed">
        <tr lang="vi"> Bạn đã đăng ký </tr>
      </string>
      <string key="You do not have permissions to post  listings.">
        <tr lang="vi"> Bạn không có quyền truy cập để tải lên danh sách. </tr>
      </string>
      <string key="No listings found.">
        <tr lang="vi"> Không có danh sách hàng </tr>
      </string>
      <string key="Listing ID is not defined">
        <tr lang="vi"> Xác định danh sách được không được định nghĩa </tr>
      </string>
      <string key="Save">
        <tr lang="vi"> Lưu </tr>
      </string>
      <string key="image format is not supported">
        <tr lang="vi"> định dạng hình ảnh không được hỗ trợ </tr>
      </string>
      <string key="You have successfully changed your profile info!">
        <tr lang="vi"> Bạn đã thay đổi thành công thông tin cá nhân của bạn! </tr>
      </string>
      <string key="Delete">
        <tr lang="vi"> Xóa </tr>
      </string>
      <string key="File deleted successfully">
        <tr lang="vi"> Tập tin đã bị xóa thành công </tr>
      </string>
      <string key="Back to edit profile">
        <tr lang="vi"> Quay lại chỉnh sửa hồ sơ </tr>
      </string>
      <string key="You have not saved any searches yet.">
        <tr lang="vi"> Bạn chưa lưu bất kỳ tìm kiếm nào. </tr>
      </string>
      <string key="ID">
        <tr lang="vi"> Xác định </tr>
      </string>
      <string key="Period">
        <tr lang="vi"> thời gian </tr>
      </string>
      <string key="State">
        <tr lang="vi">  </tr>
      </string>
      <string key="from">
        <tr lang="vi"> Từ </tr>
      </string>
      <string key="to">
        <tr lang="vi"> đến </tr>
      </string>
      <string key="Date">
        <tr lang="vi"> Ngày </tr>
      </string>
      <string key="Description">
        <tr lang="vi"> Mô tả </tr>
      </string>
      <string key="Amount">
        <tr lang="vi"> Số tiền </tr>
      </string>
      <string key="Action">
        <tr lang="vi"> Hành động </tr>
      </string>
      <string key="Total Amount">
        <tr lang="vi"> Tổng số tiền </tr>
      </string>
      <string key="There are no saved listings">
        <tr lang="vi"> Không có lưu lại danh sách </tr>
      </string>
      <string key="Notify on Listing Activation">
        <tr lang="vi"> Thông báo trên kích hoạt niêm yết </tr>
      </string>
      <string key="Notify on Listing Expiration">
        <tr lang="vi"> Thông báo thời điểm hết hạn niêm yết </tr>
      </string>
      <string key="Notify on Contract Expiration">
        <tr lang="vi"> Thông báo khi hợp đồng hết hạn </tr>
      </string>
      <string key="Modify search">
        <tr lang="vi"> Sửa đổi tìm kiếm </tr>
      </string>
      <string key="Save this search">
        <tr lang="vi"> Lưu tìm kiếm này </tr>
      </string>
      <string key="Saved jobs">
        <tr lang="vi"> Lưu công việc </tr>
      </string>
      <string key="Saved searches">
        <tr lang="vi"> Tìm kiếm đã lưu </tr>
      </string>
      <string key="Results: {$listings_number} Jobs">
        <tr lang="vi">  </tr>
      </string>
      <string key="Number of jobs per page">
        <tr lang="vi"> Số việc làm trên một trang </tr>
      </string>
      <string key="Previous">
        <tr lang="vi"> Trước </tr>
      </string>
      <string key="Save Your Search">
        <tr lang="vi"> Lưu tìm kiếm của bạn </tr>
      </string>
      <string key="Search Name">
        <tr lang="vi"> tìm kiếm Tên </tr>
      </string>
      <string key="Your search has been saved.">
        <tr lang="vi"> Tìm kiếm của bạn đã được lưu. </tr>
      </string>
      <string key="You may close this window now.">
        <tr lang="vi"> Bạn có thể đóng cửa sổ này </tr>
      </string>
      <string key="Save ad">
        <tr lang="vi"> lưu quảng cáo </tr>
      </string>
      <string key="View job details">
        <tr lang="vi"> xem chi tiết công việc </tr>
      </string>
      <string key="Rate this job">
        <tr lang="vi"> Công việc này </tr>
      </string>
      <string key="Please, Vote!">
        <tr lang="vi"> hãy bỏ phiếu </tr>
      </string>
      <string key="Watch a video">
        <tr lang="vi"> Xem video </tr>
      </string>
      <string key="Save this Job">
        <tr lang="vi"> Lưu việc làm này </tr>
      </string>
      <string key="View Saved Jobs">
        <tr lang="vi"> Coi công việc đã lưu </tr>
      </string>
      <string key="Tell a Friend">
        <tr lang="vi"> Giới thiệu với bạn bè </tr>
      </string>
      <string key="Print This Ad">
        <tr lang="vi"> In quảng cáo này </tr>
      </string>
      <string key="View Map">
        <tr lang="vi"> xem bản đồ </tr>
      </string>
      <string key="Back to Results">
        <tr lang="vi">  </tr>
      </string>
      <string key="Modify Search">
        <tr lang="vi"> sửa đổi tìm kiếm </tr>
      </string>
      <string key="Rate This Job">
        <tr lang="vi">  </tr>
      </string>
      <string key="User Info">
        <tr lang="vi">  </tr>
      </string>
      <string key="All jobs by this company">
        <tr lang="vi"> Tất cả các công việc của công ty này </tr>
      </string>
      <string key="Video">
        <tr lang="vi"> Video </tr>
      </string>
      <string key="Photos">
        <tr lang="vi"> Hình ảnh </tr>
      </string>
      <string key="Apply now">
        <tr lang="vi"> Áp dụng ngay bây giờ </tr>
      </string>
      <string key="Location">
        <tr lang="vi"> Địa điểm </tr>
      </string>
      <string key="Please, wait ...">
        <tr lang="vi"> Xin vui lòng chờ đợi... </tr>
      </string>
      <string key="Add your comment">
        <tr lang="vi"> Thêm bình luận của bạn </tr>
      </string>
      <string key="Add">
        <tr lang="vi"> Thêm </tr>
      </string>
      <string key="Listing has been saved">
        <tr lang="vi">  </tr>
      </string>
      <string key="View details">
        <tr lang="vi"> Xem chi tiết </tr>
      </string>
      <string key="Recommend listing with ID">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your name">
        <tr lang="vi"> Tên của bạn </tr>
      </string>
      <string key="Your friend\&apos;s name">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your friend\&apos;s e-mail address">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your comment (will be send with the recomendation)">
        <tr lang="vi">  </tr>
      </string>
      <string key="Send">
        <tr lang="vi"> Gửi </tr>
      </string>
      <string key="Cannot send letter">
        <tr lang="vi">  </tr>
      </string>
      <string key="Company Info">
        <tr lang="vi"> Thông tin công ty </tr>
      </string>
      <string key="You\&apos;ve already voted">
        <tr lang="vi">  </tr>
      </string>
      <string key="Author">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your e-mail">
        <tr lang="vi"> Email của bạn </tr>
      </string>
      <string key="Your request">
        <tr lang="vi"> Yêu cầu của bạn </tr>
      </string>
      <string key="Attach your resume">
        <tr lang="vi"> Đính kèm hồ sơ xin việc </tr>
      </string>
      <string key="Cannot send your message">
        <tr lang="vi"> Không thể gửi tin nhắn của bạn </tr>
      </string>
      <string key="You do not have permissions to post Resume listings.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Results: {$listings_number} Resumes">
        <tr lang="vi">  </tr>
      </string>
      <string key="Number of resumes per page">
        <tr lang="vi">  </tr>
      </string>
      <string key="Enter Your Ad Information">
        <tr lang="vi">  </tr>
      </string>
      <string key="Add Pictures">
        <tr lang="vi"> Thêm hình ảnh </tr>
      </string>
      <string key="is empty">
        <tr lang="vi">  </tr>
      </string>
      <string key="could not convert video file">
        <tr lang="vi">  </tr>
      </string>
      <string key="is unknown">
        <tr lang="vi">  </tr>
      </string>
      <string key="Manage Listing">
        <tr lang="vi"> Quản lý danh sách </tr>
      </string>
      <string key="Preview Listing">
        <tr lang="vi"> xem trước danh sách </tr>
      </string>
      <string key="Manage Listing Pictures">
        <tr lang="vi"> Quản lý hình ảnh danh sách </tr>
      </string>
      <string key="Go to Manage Listing">
        <tr lang="vi">  </tr>
      </string>
      <string key="Add Picture">
        <tr lang="vi">  </tr>
      </string>
      <string key="Caption">
        <tr lang="vi">  </tr>
      </string>
      <string key="Thumbnail">
        <tr lang="vi">  </tr>
      </string>
      <string key="Actions">
        <tr lang="vi">  </tr>
      </string>
      <string key="Are you sure?">
        <tr lang="vi">  </tr>
      </string>
      <string key="Edit Picture">
        <tr lang="vi">  </tr>
      </string>
      <string key="Picture">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please specify a valid email address.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please provide your full name.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please include your comments.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Thank you very much for your message. We will respond to you as soon as possible.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Invalid password">
        <tr lang="vi"> Mật khẩu không hợp lệ </tr>
      </string>
      <string key="Login error">
        <tr lang="vi"> Không đúng tên người dùng và / hoặc mật khẩu </tr>
      </string>
      <string key="Browse by category">
        <tr lang="vi">  </tr>
      </string>
      <string key="There are no listings with requested parameters in the system.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Browse by city">
        <tr lang="vi"> Tìm theo thành phố </tr>
      </string>
      <string key="My Resumes">
        <tr lang="vi">  </tr>
      </string>
      <string key="Saved Jobs">
        <tr lang="vi"> Công việc đã lưu </tr>
      </string>
      <string key="Job Alerts">
        <tr lang="vi"> công việc cảnh báo </tr>
      </string>
      <string key="Jobs by {$companyName}">
        <tr lang="vi">  </tr>
      </string>
      <string key="$select_box_field_distance of Zip $input_text_field_location">
        <tr lang="vi">  </tr>
      </string>
      <string key="$input_text_field_from to $input_text_field_to">
        <tr lang="vi">  </tr>
      </string>
      <string key="not confirmed">
        <tr lang="vi">  </tr>
      </string>
      <string key="this value is already used in the system">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please, enter your username in the field below and we&apos;ll send you a link to a page where you can change your password">
        <tr lang="vi">  </tr>
      </string>
      <string key="Check all">
        <tr lang="vi">  </tr>
      </string>
      <string key="Uncheck all">
        <tr lang="vi">  </tr>
      </string>
      <string key="Actions with Selected">
        <tr lang="vi">  </tr>
      </string>
      <string key="Number of listings per page">
        <tr lang="vi">  </tr>
      </string>
      <string key="Rating">
        <tr lang="vi">  </tr>
      </string>
      <string key="Deactivate">
        <tr lang="vi"> Tắt </tr>
      </string>
      <string key="Activate">
        <tr lang="vi"> Kích hoạt </tr>
      </string>
      <string key="Your listing is successfully activated">
        <tr lang="vi"> Danh sách của bạn được kích hoạt thành công </tr>
      </string>
      <string key="Back to My Listings">
        <tr lang="vi">  </tr>
      </string>
      <string key="Sort by">
        <tr lang="vi"> Sắp xếp theo </tr>
      </string>
      <string key="Edit">
        <tr lang="vi"> Chỉnh sửa </tr>
      </string>
      <string key="View Details">
        <tr lang="vi">  </tr>
      </string>
      <string key="Enable Auto notify">
        <tr lang="vi">  </tr>
      </string>
      <string key="Disable Auto notify">
        <tr lang="vi">  </tr>
      </string>
      <string key="Results: $listings_number Jobs">
        <tr lang="vi">  </tr>
      </string>
      <string key="Jobs by $companyName">
        <tr lang="vi">  </tr>
      </string>
      <string key="Results: $listings_number Resumes">
        <tr lang="vi">  </tr>
      </string>
      <string key="Rate this resume">
        <tr lang="vi">  </tr>
      </string>
      <string key="View resume details">
        <tr lang="vi">  </tr>
      </string>
      <string key="All resumes by this user">
        <tr lang="vi">  </tr>
      </string>
      <string key="Rate This Resume">
        <tr lang="vi">  </tr>
      </string>
      <string key="View Saved Resumes">
        <tr lang="vi">  </tr>
      </string>
      <string key="Save this Resume">
        <tr lang="vi">  </tr>
      </string>
      <string key="Resumes by $firstName $lastName">
        <tr lang="vi">  </tr>
      </string>
      <string key="Select a Package">
        <tr lang="vi">  </tr>
      </string>
      <string key="is not an integer value">
        <tr lang="vi">  </tr>
      </string>
      <string key="You&apos;ve got a limit of the allowed number of picture">
        <tr lang="vi">  </tr>
      </string>
      <string key="limit exceeded">
        <tr lang="vi">  </tr>
      </string>
      <string key="You don&apos;t have permissions to access this page.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Resume search is accessible only for subscribed Employers.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your friend&apos;s name">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your friend&apos;s e-mail address">
        <tr lang="vi">  </tr>
      </string>
      <string key="Dear customer!">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please make a payment in the amount of $currency_sign $product_info_price for &lt;b&gt;$product_info_name&lt;/b&gt;.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please choose from the following payment methods:">
        <tr lang="vi">  </tr>
      </string>
      <string key="Wire Transfer">
        <tr lang="vi">  </tr>
      </string>
      <string key="Dear $username, &lt;br /&gt;&lt;br /&gt;Please send us a payment in the amount of $amount for $item_name&lt;br /&gt;Your transaction reference number is $payment_id. &lt;br /&gt;&lt;br /&gt;Thank you!">
        <tr lang="vi">  </tr>
      </string>
      <string key="There is no listing in the system with the specified ID">
        <tr lang="vi">  </tr>
      </string>
      <string key="Anonymous User Info">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please make a payment in the amount of $currency_sign $product_info_price for">
        <tr lang="vi">  </tr>
      </string>
      <string key="Welcome">
        <tr lang="vi">  </tr>
      </string>
      <string key="Dear $username, &lt;br /&gt;&lt;br /&gt;Please send us a payment in the amount of $amount for">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your transaction reference number is $payment_id. &lt;br /&gt;&lt;br /&gt;Thank you!">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please log in to access this page. If you do not have an account, please">
        <tr lang="vi">  </tr>
      </string>
      <string key="Featured Companies">
        <tr lang="vi">  </tr>
      </string>
      <string key="Get resumes by email">
        <tr lang="vi">  </tr>
      </string>
      <string key="Get jobs by email">
        <tr lang="vi"> Nhận được việc làm qua email </tr>
      </string>
      <string key="Please use the &quot;Control&quot; key to choose two or more options">
        <tr lang="vi">  </tr>
      </string>
      <string key="Confirm E-mail">
        <tr lang="vi"> Xác nhận E-mail </tr>
      </string>
      <string key="Reload Image">
        <tr lang="vi">  </tr>
      </string>
      <string key="Accept terms of use">
        <tr lang="vi">  </tr>
      </string>
      <string key="Read terms of use">
        <tr lang="vi">  </tr>
      </string>
      <string key="Resume Alerts">
        <tr lang="vi">  </tr>
      </string>
      <string key="Application Tracking">
        <tr lang="vi">  </tr>
      </string>
      <string key="Resume Alert Name">
        <tr lang="vi">  </tr>
      </string>
      <string key="Add new resume alert">
        <tr lang="vi">  </tr>
      </string>
      <string key="Disable">
        <tr lang="vi">  </tr>
      </string>
      <string key="Preview Search Results">
        <tr lang="vi">  </tr>
      </string>
      <string key="Add resume alert">
        <tr lang="vi">  </tr>
      </string>
      <string key="Alert Name">
        <tr lang="vi">  </tr>
      </string>
      <string key="Job Title">
        <tr lang="vi">  </tr>
      </string>
      <string key="Date Applied">
        <tr lang="vi">  </tr>
      </string>
      <string key="Status">
        <tr lang="vi">  </tr>
      </string>
      <string key="Attached Resume">
        <tr lang="vi">  </tr>
      </string>
      <string key="Applicant’s Name">
        <tr lang="vi">  </tr>
      </string>
      <string key="User comments">
        <tr lang="vi">  </tr>
      </string>
      <string key="View Attached File">
        <tr lang="vi">  </tr>
      </string>
      <string key="Jobs Search Results">
        <tr lang="vi">  </tr>
      </string>
      <string key="Save this Search / Job Alert">
        <tr lang="vi">  </tr>
      </string>
      <string key="Company Profile">
        <tr lang="vi">  </tr>
      </string>
      <string key="Sign in">
        <tr lang="vi">  </tr>
      </string>
      <string key="You have no listings now. Click">
        <tr lang="vi">  </tr>
      </string>
      <string key="here">
        <tr lang="vi">  </tr>
      </string>
      <string key="to add a new listing.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Fields marked with an asterisk (">
        <tr lang="vi">  </tr>
      </string>
      <string key=") are mandatory">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please log in to place a listing. If you do not have an account, please">
        <tr lang="vi">  </tr>
      </string>
      <string key="within $radius $radius_search_unit of $location">
        <tr lang="vi">  </tr>
      </string>
      <string key="kilometers">
        <tr lang="vi">  </tr>
      </string>
      <string key="Apply to job">
        <tr lang="vi">  </tr>
      </string>
      <string key="Cover letter (optional)">
        <tr lang="vi">  </tr>
      </string>
      <string key="Please">
        <tr lang="vi"> xin </tr>
      </string>
      <string key="sign in ">
        <tr lang="vi">  </tr>
      </string>
      <string key="to add comments!">
        <tr lang="vi">  </tr>
      </string>
      <string key="You applied successfully">
        <tr lang="vi"> Bạn áp dụng thành công </tr>
      </string>
      <string key="Please log in to place a new posting. If you do not have an account, please">
        <tr lang="vi">  </tr>
      </string>
      <string key="Register.">
        <tr lang="vi">  </tr>
      </string>
      <string key="Search by Company">
        <tr lang="vi"> Tìm kiếm công ty </tr>
      </string>
      <string key="Clone">
        <tr lang="vi">  </tr>
      </string>
      <string key="My Job Preview">
        <tr lang="vi">  </tr>
      </string>
      <string key="Click to select">
        <tr lang="vi">  </tr>
      </string>
      <string key="Redirect to this URL">
        <tr lang="vi">  </tr>
      </string>
      <string key="Use the following format:">
        <tr lang="vi">  </tr>
      </string>
      <string key="Your changes were successfully saved">
        <tr lang="vi">  </tr>
      </string>
      <string key="Manage Pictures">
        <tr lang="vi">  </tr>
      </string>
      <string key="Clone this job posting">
        <tr lang="vi">  </tr>
      </string>
      <string key="Clone Job">
        <tr lang="vi">  </tr>
      </string>
      <string key="Company">
        <tr lang="vi">  </tr>
      </string>
      <string key="My Applications">
        <tr lang="vi">  </tr>
      </string>
      <string key="Select your resume">
        <tr lang="vi">  </tr>
      </string>
      <string key="Enter Job Information">
        <tr lang="vi">  </tr>
      </string>
      <string key="My Postings">
        <tr lang="vi">  </tr>
      </string>
      <string key="Private messages">
        <tr lang="vi">  </tr>
      </string>
      <string key="Inbox">
        <tr lang="vi">  </tr>
      </string>
      <string key="Outbox">
        <tr lang="vi">  </tr>
      </string>
      <string key="Edit Saved Search">
        <tr lang="vi">  </tr>
      </string>
      <string key="Saved Searches Name">
        <tr lang="vi">  </tr>
      </string>
      <string key="Notify on My Jobs Expiration">
        <tr lang="vi">  </tr>
      </string>
      <string key="Notify on My Contract Expiration">
        <tr lang="vi">  </tr>
      </string>
      <string key="Notify on new private message">
        <tr lang="vi">  </tr>
      </string>
      <string key="Cover Letter">
        <tr lang="vi"> Đơn xin việc </tr>
      </string>
      <string key="My Billings">
        <tr lang="vi">  </tr>
      </string>
      <string key="Compose Message">
        <tr lang="vi">  </tr>
      </string>
      <string key="From">
        <tr lang="vi"> Từ </tr>
      </string>
      <string key="Subject">
        <tr lang="vi"> Chủ đề </tr>
      </string>
      <string key="To">
        <tr lang="vi"> Để </tr>
      </string>
      <string key="Message to">
        <tr lang="vi">  </tr>
      </string>
      <string key="Message">
        <tr lang="vi">  </tr>
      </string>
      <string key="Save to outbox">
        <tr lang="vi">  </tr>
      </string>
      <string key="Send private message">
        <tr lang="vi">  </tr>
      </string>
      <string key="You are logged in already">
        <tr lang="vi">  </tr>
      </string>
      <string key="You&apos;re not allowed to open this page">
        <tr lang="vi">  </tr>
      </string>
      <string key="Send Private Message">
        <tr lang="vi">  </tr>
      </string>
      <string key="Save this Search / Resume Alert">
        <tr lang="vi">  </tr>
      </string>
      <string key="Resume has been saved">
        <tr lang="vi">  </tr>
      </string>
      <string key="Contact User">
        <tr lang="vi">  </tr>
      </string>